/// A country entry for the Complete Profile country picker.
///
/// [flagEmoji] is computed from [code] (ISO 3166-1 alpha-2) rather than
/// stored as a bundled flag image — Unicode regional-indicator symbols
/// render as flag emoji via the system font on every platform this app
/// targets, so ~200 flag image assets are never needed.
class Country {
  const Country({required this.code, required this.name});

  /// ISO 3166-1 alpha-2 code, e.g. `'MA'`.
  final String code;
  final String name;

  String get flagEmoji {
    final int base = 0x1F1E6; // Regional Indicator Symbol Letter A
    final int first = base + code.codeUnitAt(0) - 'A'.codeUnitAt(0);
    final int second = base + code.codeUnitAt(1) - 'A'.codeUnitAt(0);
    return String.fromCharCode(first) + String.fromCharCode(second);
  }
}

/// All countries, sorted alphabetically by [Country.name].
///
/// Aims for complete UN-member-state coverage (plus a small number of
/// widely-recognized non-UN territories, e.g. Taiwan, Kosovo, Vatican
/// City, Palestine) — ~195 entries, per the "must contain all countries
/// of the world" requirement.
final List<Country> kCountries = List.unmodifiable(
  <Country>[
    const Country(code: 'AF', name: 'Afghanistan'),
    const Country(code: 'AL', name: 'Albania'),
    const Country(code: 'DZ', name: 'Algeria'),
    const Country(code: 'AD', name: 'Andorra'),
    const Country(code: 'AO', name: 'Angola'),
    const Country(code: 'AG', name: 'Antigua and Barbuda'),
    const Country(code: 'AR', name: 'Argentina'),
    const Country(code: 'AM', name: 'Armenia'),
    const Country(code: 'AU', name: 'Australia'),
    const Country(code: 'AT', name: 'Austria'),
    const Country(code: 'AZ', name: 'Azerbaijan'),
    const Country(code: 'BS', name: 'Bahamas'),
    const Country(code: 'BH', name: 'Bahrain'),
    const Country(code: 'BD', name: 'Bangladesh'),
    const Country(code: 'BB', name: 'Barbados'),
    const Country(code: 'BY', name: 'Belarus'),
    const Country(code: 'BE', name: 'Belgium'),
    const Country(code: 'BZ', name: 'Belize'),
    const Country(code: 'BJ', name: 'Benin'),
    const Country(code: 'BT', name: 'Bhutan'),
    const Country(code: 'BO', name: 'Bolivia'),
    const Country(code: 'BA', name: 'Bosnia and Herzegovina'),
    const Country(code: 'BW', name: 'Botswana'),
    const Country(code: 'BR', name: 'Brazil'),
    const Country(code: 'BN', name: 'Brunei'),
    const Country(code: 'BG', name: 'Bulgaria'),
    const Country(code: 'BF', name: 'Burkina Faso'),
    const Country(code: 'BI', name: 'Burundi'),
    const Country(code: 'CV', name: 'Cabo Verde'),
    const Country(code: 'KH', name: 'Cambodia'),
    const Country(code: 'CM', name: 'Cameroon'),
    const Country(code: 'CA', name: 'Canada'),
    const Country(code: 'CF', name: 'Central African Republic'),
    const Country(code: 'TD', name: 'Chad'),
    const Country(code: 'CL', name: 'Chile'),
    const Country(code: 'CN', name: 'China'),
    const Country(code: 'CO', name: 'Colombia'),
    const Country(code: 'KM', name: 'Comoros'),
    const Country(code: 'CG', name: 'Congo'),
    const Country(code: 'CD', name: 'Congo (DRC)'),
    const Country(code: 'CR', name: 'Costa Rica'),
    const Country(code: 'CI', name: "Côte d'Ivoire"),
    const Country(code: 'HR', name: 'Croatia'),
    const Country(code: 'CU', name: 'Cuba'),
    const Country(code: 'CY', name: 'Cyprus'),
    const Country(code: 'CZ', name: 'Czechia'),
    const Country(code: 'DK', name: 'Denmark'),
    const Country(code: 'DJ', name: 'Djibouti'),
    const Country(code: 'DM', name: 'Dominica'),
    const Country(code: 'DO', name: 'Dominican Republic'),
    const Country(code: 'EC', name: 'Ecuador'),
    const Country(code: 'EG', name: 'Egypt'),
    const Country(code: 'SV', name: 'El Salvador'),
    const Country(code: 'GQ', name: 'Equatorial Guinea'),
    const Country(code: 'ER', name: 'Eritrea'),
    const Country(code: 'EE', name: 'Estonia'),
    const Country(code: 'SZ', name: 'Eswatini'),
    const Country(code: 'ET', name: 'Ethiopia'),
    const Country(code: 'FJ', name: 'Fiji'),
    const Country(code: 'FI', name: 'Finland'),
    const Country(code: 'FR', name: 'France'),
    const Country(code: 'GA', name: 'Gabon'),
    const Country(code: 'GM', name: 'Gambia'),
    const Country(code: 'GE', name: 'Georgia'),
    const Country(code: 'DE', name: 'Germany'),
    const Country(code: 'GH', name: 'Ghana'),
    const Country(code: 'GR', name: 'Greece'),
    const Country(code: 'GD', name: 'Grenada'),
    const Country(code: 'GT', name: 'Guatemala'),
    const Country(code: 'GN', name: 'Guinea'),
    const Country(code: 'GW', name: 'Guinea-Bissau'),
    const Country(code: 'GY', name: 'Guyana'),
    const Country(code: 'HT', name: 'Haiti'),
    const Country(code: 'HN', name: 'Honduras'),
    const Country(code: 'HU', name: 'Hungary'),
    const Country(code: 'IS', name: 'Iceland'),
    const Country(code: 'IN', name: 'India'),
    const Country(code: 'ID', name: 'Indonesia'),
    const Country(code: 'IR', name: 'Iran'),
    const Country(code: 'IQ', name: 'Iraq'),
    const Country(code: 'IE', name: 'Ireland'),
    const Country(code: 'IL', name: 'Israel'),
    const Country(code: 'IT', name: 'Italy'),
    const Country(code: 'JM', name: 'Jamaica'),
    const Country(code: 'JP', name: 'Japan'),
    const Country(code: 'JO', name: 'Jordan'),
    const Country(code: 'KZ', name: 'Kazakhstan'),
    const Country(code: 'KE', name: 'Kenya'),
    const Country(code: 'KI', name: 'Kiribati'),
    const Country(code: 'XK', name: 'Kosovo'),
    const Country(code: 'KW', name: 'Kuwait'),
    const Country(code: 'KG', name: 'Kyrgyzstan'),
    const Country(code: 'LA', name: 'Laos'),
    const Country(code: 'LV', name: 'Latvia'),
    const Country(code: 'LB', name: 'Lebanon'),
    const Country(code: 'LS', name: 'Lesotho'),
    const Country(code: 'LR', name: 'Liberia'),
    const Country(code: 'LY', name: 'Libya'),
    const Country(code: 'LI', name: 'Liechtenstein'),
    const Country(code: 'LT', name: 'Lithuania'),
    const Country(code: 'LU', name: 'Luxembourg'),
    const Country(code: 'MG', name: 'Madagascar'),
    const Country(code: 'MW', name: 'Malawi'),
    const Country(code: 'MY', name: 'Malaysia'),
    const Country(code: 'MV', name: 'Maldives'),
    const Country(code: 'ML', name: 'Mali'),
    const Country(code: 'MT', name: 'Malta'),
    const Country(code: 'MH', name: 'Marshall Islands'),
    const Country(code: 'MR', name: 'Mauritania'),
    const Country(code: 'MU', name: 'Mauritius'),
    const Country(code: 'MX', name: 'Mexico'),
    const Country(code: 'FM', name: 'Micronesia'),
    const Country(code: 'MD', name: 'Moldova'),
    const Country(code: 'MC', name: 'Monaco'),
    const Country(code: 'MN', name: 'Mongolia'),
    const Country(code: 'ME', name: 'Montenegro'),
    const Country(code: 'MA', name: 'Morocco'),
    const Country(code: 'MZ', name: 'Mozambique'),
    const Country(code: 'MM', name: 'Myanmar'),
    const Country(code: 'NA', name: 'Namibia'),
    const Country(code: 'NR', name: 'Nauru'),
    const Country(code: 'NP', name: 'Nepal'),
    const Country(code: 'NL', name: 'Netherlands'),
    const Country(code: 'NZ', name: 'New Zealand'),
    const Country(code: 'NI', name: 'Nicaragua'),
    const Country(code: 'NE', name: 'Niger'),
    const Country(code: 'NG', name: 'Nigeria'),
    const Country(code: 'KP', name: 'North Korea'),
    const Country(code: 'MK', name: 'North Macedonia'),
    const Country(code: 'NO', name: 'Norway'),
    const Country(code: 'OM', name: 'Oman'),
    const Country(code: 'PK', name: 'Pakistan'),
    const Country(code: 'PW', name: 'Palau'),
    const Country(code: 'PS', name: 'Palestine'),
    const Country(code: 'PA', name: 'Panama'),
    const Country(code: 'PG', name: 'Papua New Guinea'),
    const Country(code: 'PY', name: 'Paraguay'),
    const Country(code: 'PE', name: 'Peru'),
    const Country(code: 'PH', name: 'Philippines'),
    const Country(code: 'PL', name: 'Poland'),
    const Country(code: 'PT', name: 'Portugal'),
    const Country(code: 'QA', name: 'Qatar'),
    const Country(code: 'RO', name: 'Romania'),
    const Country(code: 'RU', name: 'Russia'),
    const Country(code: 'RW', name: 'Rwanda'),
    const Country(code: 'KN', name: 'Saint Kitts and Nevis'),
    const Country(code: 'LC', name: 'Saint Lucia'),
    const Country(code: 'VC', name: 'Saint Vincent and the Grenadines'),
    const Country(code: 'WS', name: 'Samoa'),
    const Country(code: 'SM', name: 'San Marino'),
    const Country(code: 'ST', name: 'Sao Tome and Principe'),
    const Country(code: 'SA', name: 'Saudi Arabia'),
    const Country(code: 'SN', name: 'Senegal'),
    const Country(code: 'RS', name: 'Serbia'),
    const Country(code: 'SC', name: 'Seychelles'),
    const Country(code: 'SL', name: 'Sierra Leone'),
    const Country(code: 'SG', name: 'Singapore'),
    const Country(code: 'SK', name: 'Slovakia'),
    const Country(code: 'SI', name: 'Slovenia'),
    const Country(code: 'SB', name: 'Solomon Islands'),
    const Country(code: 'SO', name: 'Somalia'),
    const Country(code: 'ZA', name: 'South Africa'),
    const Country(code: 'KR', name: 'South Korea'),
    const Country(code: 'SS', name: 'South Sudan'),
    const Country(code: 'ES', name: 'Spain'),
    const Country(code: 'LK', name: 'Sri Lanka'),
    const Country(code: 'SD', name: 'Sudan'),
    const Country(code: 'SR', name: 'Suriname'),
    const Country(code: 'SE', name: 'Sweden'),
    const Country(code: 'CH', name: 'Switzerland'),
    const Country(code: 'SY', name: 'Syria'),
    const Country(code: 'TW', name: 'Taiwan'),
    const Country(code: 'TJ', name: 'Tajikistan'),
    const Country(code: 'TZ', name: 'Tanzania'),
    const Country(code: 'TH', name: 'Thailand'),
    const Country(code: 'TL', name: 'Timor-Leste'),
    const Country(code: 'TG', name: 'Togo'),
    const Country(code: 'TO', name: 'Tonga'),
    const Country(code: 'TT', name: 'Trinidad and Tobago'),
    const Country(code: 'TN', name: 'Tunisia'),
    const Country(code: 'TR', name: 'Turkey'),
    const Country(code: 'TM', name: 'Turkmenistan'),
    const Country(code: 'TV', name: 'Tuvalu'),
    const Country(code: 'UG', name: 'Uganda'),
    const Country(code: 'UA', name: 'Ukraine'),
    const Country(code: 'AE', name: 'United Arab Emirates'),
    const Country(code: 'GB', name: 'United Kingdom'),
    const Country(code: 'US', name: 'United States'),
    const Country(code: 'UY', name: 'Uruguay'),
    const Country(code: 'UZ', name: 'Uzbekistan'),
    const Country(code: 'VU', name: 'Vanuatu'),
    const Country(code: 'VA', name: 'Vatican City'),
    const Country(code: 'VE', name: 'Venezuela'),
    const Country(code: 'VN', name: 'Vietnam'),
    const Country(code: 'YE', name: 'Yemen'),
    const Country(code: 'ZM', name: 'Zambia'),
    const Country(code: 'ZW', name: 'Zimbabwe'),
  ]..sort((a, b) => a.name.compareTo(b.name)),
);
